# # # # # # # # # #
#  K i k o f r i  #
# # # # # # # # # #

# # # # #
# Used as meta-data for 'head.html' among 
# other things.
#
# Basic, either your jekyll site's name or
# an organization.
name: "Flatline"
description: "{diario, appunti, valvola di sfogo} personale"

# This should be a person of some sort.
author: "davide"

# Would make sense to use the 'name:' above
# here. This is an alternative title.
title: "Flatline - a personal rantbook"

# 'en_US' is the default language. Enter a
# new default language here. Making 'en_US'
# an alternative language. See 'head.html'
lang: it_IT

# Default post and page image if it's those
# are unspecified.
image: /assets/images/kikofrieye.png

# I just set this to whatever the above
# image value is.
# Could be some other image though.
logo:
#
# # # # #

# URL-stuff, don't forget the 'http...'-part
url: "https://your.own.url.net"
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
 - name: "about"
   href: "/about"

 - name: "tags"
   href: "/tags"

 - name: "feed"
   href: "/feed.xml"

 - name: "contact"
   href: "/mailto:davideparisi@gmail.com"
